version: '3.5'

services:
  money-challenge:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/src/app'
      - '/src/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - money-challenge-server

  money-challenge-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - './server:/src/app/server'
      - '/src/app/server/node_modules'
    ports:
      - 5001:5001

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.all
    ports:
      - 3050:80